phase: test
num_joint: 22
weights: ./work_dir/df/distilled_r2et_ret-40.pt
device: ['cpu'] # [0]
save_path: ./inference/student/foot_contact_1
k: 0.8

load_inp_data:
  inp_shape_path: ./datasets/mixamo/shape/Steve.npz
  tgt_shape_path: ./datasets/mixamo/shape/Claire.npz
  stats_path: ./datasets/r2et/stats
  inp_bvh_path: ./datasets/mixamo/char/Steve/martelo 3.bvh
  tgt_bvh_path: ./datasets/mixamo/char/Claire/martelo 3.bvh

ret_model_args:
  num_joint: 22
  token_channels: 64
  hidden_channels_p: 256 # 128 # 256
  embed_channels_p: 128
  kp: 1.0