phase: test
num_joint: 22
weights: ./pretrain/shape_aware.pt
device: [0]
save_path: ./datasets/r2et/Claire/
k: 0.8

load_inp_data:
  inp_shape_dir_path: ./datasets/mixamo/shape/
  tgt_shape_path: ./datasets/mixamo/shape/Claire.npz
  stats_path: ./datasets/mixamo/stats/
  inp_q_dir_path: ./datasets/mixamo/q/
  tgt_q_path: ./datasets/mixamo/bvh/Claire.bvh

ret_model_args:
  num_joint: 22
  token_channels: 64
  hidden_channels_p: 256
  embed_channels_p: 128
  kp: 1.0